### ISSUE TITLE
Error: Cannot find module 'xctestwd-frameworks-10.0'

### ISSUE THREAD

**Issue by liyinchigithub** [macacajs/XCTestWD#145]
运行环境macbook 10.13平台
执行npm i macaca-ios -g 报错内容如下：

> xctestwd@1.3.32 install /Users/liyinchi/TestTool/node-v8.11.4-darwin-x64/lib/node_modules/macaca-ios/node_modules/xctestwd
> node ./scripts/install.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'xctestwd-frameworks-10.0'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/liyinchi/TestTool/node-v8.11.4-darwin-x64/lib/node_modules/macaca-ios/node_modules/xctestwd/scripts/install.js:73:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xctestwd@1.3.32 install: `node ./scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xctestwd@1.3.32 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

PS：
①macaca-doctor环境没问题
②npm search xctestwd 最新的版本没有10.0

**Comment by xudafeng** [comment]
try again
