### ISSUE TITLE
Internal Server Error displays in browser after launching the inspector for iOS device

### ISSUE THREAD

**Issue by ssmalan94** [macacajs/XCTestWD#147]
In Macaca doctor getting this : 
macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.10.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
TypeError: Invalid Version: 9.4.1.0
    at new SemVer (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:305:11)
    at compare (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:578:10)
    at Function.lt (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:612:10)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

In Console:

>> XCTestWD version: 1.4.4
undefined
>> iOS device started: d65a23cce96269b7a6b162e5bd8dcf0a6a82447a
>> inspector start at: http://10.207.203.34:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by SamuelZhaoY** [comment]
XCTestWD requires to use xcode 10.0 and above since it is now using swift 4.2
